---
title: "Penguins"
format: 
  html: default
  typst:
    template-partials:  
      - typst-show.typ
      - typst-template.typ
params:
  species: Gentoo
echo: false
message: false
warning: false
    
---

```{r}
#| include: false
# library(glue)
# library(tidyverse)
# library(palmerpenguins)
# library(kableExtra)
# library(gghighlight)
# library(quarto)
pacman::p_load(glue,dplyr,ggplot2,palmerpenguins,gghighlight,showtext,quarto,purrr,tidyr,tinytable)

```
```{r}
#| output: asis
#| echo: false
write_yaml_metadata_block(params = list(species = params$species))

# cat(sprintf("\n\n---\nspecies: %s\n---\n\n", params[["species"]]))
```

```{r}
#| include: false
# Define species color schemes

species_colors <- data.frame(
  species = c("Adelie", "Chinstrap", "Gentoo"),
  primary = c("#FF6B35", "#7209B7", "#047075"),
  secondary = c("#004E89", "#A8A83B", "#EDBF07"),
  stringsAsFactors = FALSE
)

color <- case_when(params$species == "Adelie" ~ "#FF6600",
                   params$species == "Gentoo" ~ "#047075",
                   params$species == "Chinstrap" ~ "#C25BCC")

current_colors <- species_colors[species_colors$species == params$species, ]
sidebar_color <- current_colors$primary
header_color <- current_colors$secondary

```


```{=typst}

#set page(background: place(
        top,
        rect(
            width: 2cm,
            height: 100%,
            fill: rgb(`r shQuote(sidebar_color)`)
        )
    ),
    foreground: place(
        top+right,
        dx: -1.9cm, dy: 0.7cm, image("penguins.png",width: 4cm)
    )
)
#h(-1cm)
    #box(
        fill: rgb(`r shQuote(header_color)`),
        width: 13cm,
        inset: 10pt,
    )[
        #text(size: 2.5em, fill: white)[*{{< meta title >}}*]
    ]

*#text(size: 1.2em)[Species: `{r} params[["species"]]`]* 
#show heading.where(level: 1): it => {
  set text(fill: rgb(`r shQuote(color)`)) // Set title color
  it // Render the heading itself
  v(-0.3cm)
  line(length: 100%, stroke: 1pt +rgb(`r shQuote(color)`))
  v(0.5cm)
}
 
```

  
The `r params$species` penguins can be found on the island(s) of: `r glue_collapse(penguins |> filter(species == params$species) |> count(island) |> pluck(1), sep = ", ", last = ", and ")`.

# Mass
::: {.align ="center"}
```{r table}
penguins %>%  
  filter(!is.na(sex)) %>% 
  group_by(species, sex) |> 
  summarize(mass = round(mean(body_mass_g, na.rm = TRUE), 1)) |> 
  tt(width = 0.7)  |> 
  setNames(c("Species","Sex","Average Mass (g)")) |>
  style_tt(i=0,bold=TRUE)  |> 
  style_tt(align="c") |> 
  style_tt(species == params$species, color = color, bold=TRUE) 
```
:::

# Bills

```{r scatter}
#| fig-height: 3
#| fig-align: center
library(showtext)
font_add_google(name = "Prompt", 
                family = "prompt")
showtext_auto()
penguin_theme <- function () { 
  theme_linedraw(base_size=11, base_family="prompt") %+replace% 
    theme(
      panel.background  = element_blank(),
      plot.background = element_rect(fill = "transparent", color = NA), 
      axis.ticks = element_blank(),
      panel.grid.major = element_line(color = "grey90", size = 0.3), 
      panel.grid.minor = element_blank(),
      axis.text.x = element_text(size = 13),
      axis.text.y = element_text(size = 13)
    )
}

penguins |> 
  drop_na() |>
        ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species))  +
        geom_point(size = 3) +
        labs(x = "Bill length in mm", y = "Bill depth in mm") +
        gghighlight(species == params$species)+
        penguin_theme()+
        gghighlight(species==params$species)+
        scale_color_manual(values =c("Adelie"="#FF6600",
                                     "Gentoo"="#047075",
                                     "Chinstrap"="#C25BCC") )+
        geom_point(size=3)
```